### ISSUE TITLE
program crashes when I try to save or print the generated Stark map

### ISSUE THREAD

**Issue by Zeudi** [pairinteraction/pairinteraction#57] opened 2017-05-09 13:03 UTC
![error](https://cloud.githubusercontent.com/assets/26708254/25851982/1fbf3650-34c8-11e7-867c-fa36ab048a01.png)

I managed to "catch" the lightening error appearing before the code crashes each time I try to save or print a map.

I tried to edit the app.py macro but it seems I cannot.. it prevents me doing any change on the code.

The programs runs normally, sometimes crashing when the input values are not correct, but this is not a big issue.
I am not a computer expert, I just copy&pasted the folder "pairinteraction" in my programs folder..

Thank you in advance

**Comment by seweber** [comment] 2017-05-09 14:41
Thank you for reporting this issue. It seems to be the same as #52. Have you tried our last release  v0.4-alpha? There, this issue should actually be fixed.

**Comment by Zeudi** [comment] 2017-05-09 15:17
Actually with that release the program didn't start at all... it crashed immediately while launching it..

**Comment by seweber** [comment] 2017-05-09 17:26
Thanks a lot for this information. This bug was new to us. Now, it is also fixed. You can download the bug-fixed release v0.5-alpha from https://github.com/seweber/pairinteraction/releases. Within the next day, the new release will be made available on the official homepage, too.

**Comment by Zeudi** [comment] 2017-05-09 18:24
![error - copie 2](https://cloud.githubusercontent.com/assets/26708254/25865957/12a9be18-34f5-11e7-92ad-10e4a39de8bf.png)

Here you see the new error... I tryed to add this folder because in the program I had it was present in Miniconda3, but after this other modules errors were found.. for example on PyQt5 (here I didn't know how to move because it is the first and only folder inside sip) and there was some error maybe in QtCore and QtGui..

**Comment by seweber** [comment] 2017-05-09 19:23
Hmm, strange ... I checked it with Windows 10 and everything was working fine, now. It worked without adding any folder manually. What happens if you deinstall the program completely and afterwards reinstall it without adding any folder manually? Please ensure that all the components of the program are installed (i.e., all the check boxes in the installation window should be marked).

Concerning "sip", I expect that this library is not really needed. So, if the "import sip" statement causes problems inside gui/pairinteraction/app.py, it should be save to remove this statement.

**Comment by Zeudi** [comment] 2017-05-09 21:46
Sorry for writing, but I have just checked the code on windows 10, given that you test on it, and it works.
The same code still doesn't work for windows 7. I used exactly the same .exe to run the installation.

![windows7](https://cloud.githubusercontent.com/assets/26708254/25874101/56d88cec-3511-11e7-97c9-ef0edcf99e56.png)

The error appearing now is only the second one shown above on PyQt5, but now the line is 35 and not 36.

**Comment by hmenke** [comment] 2017-05-09 22:00
This looks very much like the installation went wrong somehow and Miniconda did not properly install PyQt5.  That might be because Miniconda broke PyQt5.  I remember that we switched to the Miniconda version of PyQt5 because it broke on PyPI.  They might now have pulled the same tainted version into Miniconda.

\*sigh\* I will have a look at some point...

**Comment by juliusdh** [comment] 2017-05-10 15:15
I was getting the same error Zeudi reported [above](https://github.com/pairinteraction/pairinteraction/issues/57#issuecomment-300197896), then I upgraded to v0.5-alpha. I uninstalled everything beforehand, but after installing again, it did not launch on my (Windows 10) system either, resulting in the following error:
![pair-error](https://cloud.githubusercontent.com/assets/26091492/25906149/2640d2a4-35a4-11e7-8a0d-aeee599f7db2.PNG)

**Comment by Zeudi** [comment] 2017-05-15 17:09
Hello

I found this in the installation log. I hope it is of some help!

Zeudi
_____________________________

ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'defaults::qt-5.6.2-vc14_3'.
UnicodeDecodeError('utf-8', b'        1 fichier(s) copi\x82(s).\r\n', 25, 26, 'invalid start byte')
Attempting to roll back.

UnicodeDecodeError('utf-8', b'        1 fichier(s) copi\x82(s).\r\n', 25, 26, 'invalid start byte')

**Comment by hmenke** [comment] 2017-05-15 21:36
This confirms what I had suspected before.

However, this is allegedly fixed in Anaconda, see https://github.com/conda/conda/issues/4567

**Comment by seweber** [comment] 2017-05-28 11:30
I heard from another person that the program works again with windows 7. It seems that the fix in Anaconda indeed solved the problem.

@juliusdh I cannot reproduce this error, but I think that it is caused by an old settings file inside the ~/pairinteraction folder that survived the deinstallation of the software. The new release v0.6-alpha resets this file so that this error should be gone.

In my opinion, it would be nice if the windows uninstaller had an option for deleting the ~/pairinteraction folder. I opened a new issue #61.

**Comment by juliusdh** [comment] 2017-05-29 09:09
@seweber Fantastic, this solved my problem. I removed the cache directory that was stored in my Windows userdir (C:\Users\...\pairinteraction), reinstalled the software, and now it's churning along again!

**Closed** 2017-05-29 22:33 UTC
Labels: bug
